// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string `json:"id"`
	Detail string `json:"detail"`
	UserID string `json:"user_id"`
}

type Premiumtype struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
